/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    businessUsers: BusinessUserAuthOperations;
    donors: DonorAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    businesses: Business;
    businessUsers: BusinessUser;
    donors: Donor;
    items: Item;
    donations: Donation;
    reservations: Reservation;
    verifications: Verification;
    'verification-keys': VerificationKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    businesses: BusinessesSelect<false> | BusinessesSelect<true>;
    businessUsers: BusinessUsersSelect<false> | BusinessUsersSelect<true>;
    donors: DonorsSelect<false> | DonorsSelect<true>;
    items: ItemsSelect<false> | ItemsSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    verifications: VerificationsSelect<false> | VerificationsSelect<true>;
    'verification-keys': VerificationKeysSelect<false> | VerificationKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    'business-count': BusinessCountWidget;
    'verification-count': VerificationCountWidget;
    'donor-count': DonorCountWidget;
    'donation-count': DonationCountWidget;
    'item-count': ItemCountWidget;
    collections: CollectionsWidget;
  };
  user: User | BusinessUser | Donor;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface BusinessUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface DonorAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses".
 */
export interface Business {
  id: string;
  placeId: string;
  businessName: string;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  address?: string | null;
  streetNumber?: string | null;
  city?: string | null;
  postalCode?: string | null;
  state?: string | null;
  country?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location: [number, number];
  inactive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businessUsers".
 */
export interface BusinessUser {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  pushToken?: string | null;
  ownedBusinesses?: (string | Business)[] | null;
  staffBusinesses?: (string | Business)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'businessUsers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donors".
 */
export interface Donor {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  pushToken?: string | null;
  magicLinkToken?: string | null;
  magicLinkExpiry?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'donors';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items".
 */
export interface Item {
  id: string;
  business: string | Business;
  title?: string | null;
  description?: string | null;
  archived: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: string;
  item: string | Item;
  business: string | Business;
  /**
   * The staff member who has submitted this donation to the system.
   */
  createdBy?: (string | null) | BusinessUser;
  /**
   * The staff member who has handed this donation out.
   */
  redeemedBy?: (string | null) | BusinessUser;
  /**
   * [DEPRECATED] Use donatedBy instead
   */
  donorName?: string | null;
  donatedBy?: (string | null) | Donor;
  redeemedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: string;
  donation: string | Donation;
  /**
   * The anonymous ID of the device that is reserving this donation.
   */
  deviceId: string;
  /**
   * 6-digit PIN the claimant must present to redeem.
   */
  pin: string;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications".
 */
export interface Verification {
  id: string;
  business?: (string | null) | Business;
  /**
   * Google Maps place id
   */
  placeId: string;
  businessUser: string | BusinessUser;
  verificationEmail?: string | null;
  verificationPhone?: string | null;
  connectionType: 'admin' | 'user';
  verificationMode: 'email' | 'phone' | 'other';
  verificationNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-keys".
 */
export interface VerificationKey {
  id: string;
  verification: string | Verification;
  key: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'businesses';
        value: string | Business;
      } | null)
    | ({
        relationTo: 'businessUsers';
        value: string | BusinessUser;
      } | null)
    | ({
        relationTo: 'donors';
        value: string | Donor;
      } | null)
    | ({
        relationTo: 'items';
        value: string | Item;
      } | null)
    | ({
        relationTo: 'donations';
        value: string | Donation;
      } | null)
    | ({
        relationTo: 'reservations';
        value: string | Reservation;
      } | null)
    | ({
        relationTo: 'verifications';
        value: string | Verification;
      } | null)
    | ({
        relationTo: 'verification-keys';
        value: string | VerificationKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'businessUsers';
        value: string | BusinessUser;
      }
    | {
        relationTo: 'donors';
        value: string | Donor;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'businessUsers';
        value: string | BusinessUser;
      }
    | {
        relationTo: 'donors';
        value: string | Donor;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses_select".
 */
export interface BusinessesSelect<T extends boolean = true> {
  placeId?: T;
  businessName?: T;
  phone?: T;
  email?: T;
  website?: T;
  address?: T;
  streetNumber?: T;
  city?: T;
  postalCode?: T;
  state?: T;
  country?: T;
  location?: T;
  inactive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businessUsers_select".
 */
export interface BusinessUsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  pushToken?: T;
  ownedBusinesses?: T;
  staffBusinesses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donors_select".
 */
export interface DonorsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  pushToken?: T;
  magicLinkToken?: T;
  magicLinkExpiry?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items_select".
 */
export interface ItemsSelect<T extends boolean = true> {
  business?: T;
  title?: T;
  description?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  item?: T;
  business?: T;
  createdBy?: T;
  redeemedBy?: T;
  donorName?: T;
  donatedBy?: T;
  redeemedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  donation?: T;
  deviceId?: T;
  pin?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications_select".
 */
export interface VerificationsSelect<T extends boolean = true> {
  business?: T;
  placeId?: T;
  businessUser?: T;
  verificationEmail?: T;
  verificationPhone?: T;
  connectionType?: T;
  verificationMode?: T;
  verificationNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-keys_select".
 */
export interface VerificationKeysSelect<T extends boolean = true> {
  verification?: T;
  key?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-count_widget".
 */
export interface BusinessCountWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'small' | 'medium';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-count_widget".
 */
export interface VerificationCountWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'small' | 'medium';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donor-count_widget".
 */
export interface DonorCountWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'small' | 'medium';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-count_widget".
 */
export interface DonationCountWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'small' | 'medium';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "item-count_widget".
 */
export interface ItemCountWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'small' | 'medium';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}